apps:
  cv:
    url:
      website: http://laelem-cv.herokuapp.com
      github: https://github.com/laelem/cv
  shared_directory:
    url:
      website: http://laelem-shared-directory.herokuapp.com
      doc: "https://github.com/laelem/shared_directory#annuaire-partag%C3%A9"
      github: https://github.com/laelem/shared_directory
  sample_app:
    url:
      website: https://laelem-sampleapp-railstutorial.herokuapp.com
      github: https://github.com/laelem/sample_app